services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app
    networks:
      - shared-kafka-net
    restart: on-failure
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgres:15
    container_name: ois-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ois
    volumes:
     - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-kafka-net

volumes:
  postgres_data:

networks:
  shared-kafka-net:
    name: shared-kafka-net