services:
  ois-service:
    build:
      context: .
      target: dev
    container_name: ois-service
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=dev
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app
    networks:
      - shared-kafka-net
    restart: on-failure
    command: ["python", "-Xfrozen_modules=off", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:15
    container_name: ois-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ois
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-kafka-net

volumes:
  postgres_data:

networks:
  shared-kafka-net:
    external: true