version: "3.8"

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - shared-kafka-net
    restart: on-failure

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ois
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-kafka-net

volumes:
  postgres_data:

networks:
  shared-kafka-net:
    external: true
