"""Modify outbox_enent table

Revision ID: 95e5b37c02ce
Revises: 25414f30739b
Create Date: 2025-10-23 16:00:16.723987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95e5b37c02ce'
down_revision: Union[str, Sequence[str], None] = '25414f30739b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('aggregate_type', sa.String(length=100), nullable=False))
    op.add_column('outbox_events', sa.Column('aggregate_id', sa.String(length=100), nullable=False))
    op.add_column('outbox_events', sa.Column('event_type', sa.String(length=100), nullable=False))
    op.add_column('outbox_events', sa.Column('payload', sa.JSON(), nullable=False))
    op.add_column('outbox_events', sa.Column('status', sa.String(length=20), server_default='NEW', nullable=False))
    op.drop_column('outbox_events', 'attempts')
    op.drop_column('outbox_events', 'value')
    op.drop_column('outbox_events', 'sent_at')
    op.drop_column('outbox_events', 'topic')
    op.drop_column('outbox_events', 'headers')
    op.drop_column('outbox_events', 'sent')
    op.drop_column('outbox_events', 'last_error')
    op.drop_column('outbox_events', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('outbox_events', sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('outbox_events', sa.Column('sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('outbox_events', sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('outbox_events', sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('outbox_events', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('outbox_events', sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('outbox_events', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('outbox_events', 'status')
    op.drop_column('outbox_events', 'payload')
    op.drop_column('outbox_events', 'event_type')
    op.drop_column('outbox_events', 'aggregate_id')
    op.drop_column('outbox_events', 'aggregate_type')
    # ### end Alembic commands ###
