"""bucket is independent from order

Revision ID: dfdfb0a1c4ea
Revises: e1bfa5f938f1
Create Date: 2025-07-24 13:56:34.091942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfdfb0a1c4ea'
down_revision: Union[str, Sequence[str], None] = 'e1bfa5f938f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bucket_order_id_fkey'), 'bucket', type_='foreignkey')
    op.create_foreign_key(None, 'bucket', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucket', type_='foreignkey')
    op.create_foreign_key(op.f('bucket_order_id_fkey'), 'bucket', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
