"""order type string

Revision ID: e1af7332a6cf
Revises: 9ee3a11c2e52
Create Date: 2025-07-24 15:10:09.061522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1af7332a6cf'
down_revision: Union[str, Sequence[str], None] = '9ee3a11c2e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_type',
               existing_type=postgresql.ENUM('loading', 'unloading', 'place_changing', name='ordertype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('loading', 'unloading', 'place_changing', name='ordertype'),
               existing_nullable=False)
    # ### end Alembic commands ###
