"""Added bucket and position model

Revision ID: e1bfa5f938f1
Revises: 65ffa5e8a285
Create Date: 2025-07-23 12:39:30.823875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bfa5f938f1'
down_revision: Union[str, Sequence[str], None] = '65ffa5e8a285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('position_z', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_id'), 'position', ['id'], unique=False)
    op.create_table('bucket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('material_qty', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id')
    )
    op.create_index(op.f('ix_bucket_id'), 'bucket', ['id'], unique=False)
    op.add_column('orders', sa.Column('priority', sa.Integer(), nullable=False))
    op.drop_column('orders', 'material_id')
    op.drop_column('orders', 'qty')
    op.drop_column('orders', 'bucket_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('bucket_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'priority')
    op.drop_index(op.f('ix_bucket_id'), table_name='bucket')
    op.drop_table('bucket')
    op.drop_index(op.f('ix_position_id'), table_name='position')
    op.drop_table('position')
    # ### end Alembic commands ###
